spring:
  config:
    activate:
      on-profile: supabase

  datasource:
    url: jdbc:postgresql://db.jpgolflujsljlhxxdrhm.supabase.co:5432/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "f$f3KvVY/$nv+s2"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false

  sql:
    init:
      mode: never
