
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: mickle-muckle-api
  lifecycle:
    timeout-per-shutdown-phase: 30s

  profiles:
#    active: h2
    active: docker
#    active: supabase

  config:
    import:
      - classpath:/config/application-h2.yml
      - classpath:/config/application-docker.yml
      - classpath:/config/application-supabase.yml

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jwt:
  secret: this-is-mickle-muckle-jwt-secret-key-must-be-at-least-64-characters-long
  expiration: 86400000